name: On PR opened

on:
  pull_request:
    # types:
    #   - opened

jobs:
  set-assignee:
    name: Set assignee
    runs-on: self-hosted

    steps:
      - uses: actions/github-script@v6
        env:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));

            const query = `query($owner:String!, $name: $String!, $prNumber:String!){
              repository(owner: "songmatrix", name: "sync-service") {
                pullRequest(number: 4) {
                  closingIssuesReferences(first: 1) {
                    edges {
                      node {
                        number
                      }
                    }
                  }
                }
              }
            }  
            }`;

            const variables = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              prNumber: context.event.pull_request.number,
            };

            const result = await github.graphql(query, variables);

            console.log(JSON.stringify(result, null, 2));
