name: On PR opened

on:
  pull_request:
    # types:
    #   - opened

jobs:
  set-assignee:
    name: Set assignee
    runs-on: self-hosted

    steps:
      - uses: ./.github/actions/set-pr-issue-assignee
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.repository.name }}
          pr-number: ${{ github.event.pull_request.number }}
